export enum EUserAuthenticationErrorStatus {
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED",
    AUTHENTICATION_EXPIRED = "AUTHENTICATION_EXPIRED",
    INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
    INACTIVE_ACCESS_TOKEN = "INACTIVE_ACCESS_TOKEN"
}