export enum EDatabaseErrorStatus {
    DATA_INSERTION_ERROR = "DATABASE_INSERTION_ERROR",
    DATA_RETRIEVAL_ERROR = "DATABASE_RETRIEVAL_ERROR",
    DATA_UPDATE_ERROR = "DATABASE_UPDATE_ERROR",
    DATA_REMOVAL_ERROR = "DATABASE_REMOVAL_ERROR",
    DATA_VERIFICATION_ERROR = "DATABASE_VERIFICATION_ERROR"
}