export enum EDatabaseErrorStatus {
    DATA_INSERTION_ERROR = "DATA_INSERTION_ERROR",
    DATA_RETRIEVAL_ERROR = "DATA_RETRIEVAL_ERROR",
    DATA_UPDATE_ERROR = "DATA_UPDATE_ERROR",
    DATA_REMOVAL_ERROR = "DATA_REMOVAL_ERROR",
    DATA_VERIFICATION_ERROR = "DATA_VERIFICATION_ERROR"
}