export enum EDatabaseErrorStatus {
    DATABASE_INSERTION_ERROR = "DATABASE_INSERTION_ERROR",
    DATABASE_RETRIEVAL_ERROR = "DATABASE_RETRIEVAL_ERROR",
    DATABASE_UPDATE_ERROR = "DATABASE_UPDATE_ERROR",
    DATABASE_REMOVAL_ERROR = "DATABASE_REMOVAL_ERROR",
    DATABASE_TRANSACTION_ERROR = "DATABASE_TRANSACTION_ERROR",
    DATABASE_VERIFICATION_ERROR = "DATABASE_VERIFICATION_ERROR"
}