export enum ERequestErrorStatus {
    NOT_FOUND = "NOT_FOUND",
    MISSING_FIELDS = "MISSING_FIELDS",
    VALUELESS_FIELDS = "VALUELESS_FIELDS",
    INVALID_FIELD = "INVALID_FIELD",
    EMPTY_FIELDS = "EMPTY_FIELDS",
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
}