export enum ERequestErrorStatus {
    NOT_FOUND = "NOT_FOUND",
    MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS",
    MISSING_ACCEPTABLE_FIELDS = "MISSING_ACCEPTABLE_FIELDS",
    VALUELESS_FIELDS = "VALUELESS_FIELDS",
    INVALID_FIELD = "INVALID_FIELD",
    EMPTY_FIELDS = "EMPTY_FIELDS",
    BAD_REQUEST = "BAD_REQUEST",
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
    CONFLICT = "CONFLICT",
}